# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20150601_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_late_reserve_changes',
            field=models.BooleanField(
                default=True,
                verbose_name='Allow moving someone from reserve to attending when the event is about to start'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='late_signup_time_hours',
            field=models.IntegerField(default=5),
        ),
    ]
