# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventsignup_on_reserve_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='order_id',
        ),
    ]
