# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventsignup_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_late_reserve_changes',
            field=models.BooleanField(default=True, verbose_name='Allow moving someone from reserve to attending when the event is about to start. (set to 5 hours by default)'),
        ),
    ]
