from django.conf.urls import url

from . import views

urlpatterns = [
    url('^$',
        views.boards_main,
        name='boards_main'),

    url(r'^role/(?P<role_id>\d+)$',
        views.view_role,
        name='boards_view_role'),
    url(r'^add_role/$',
        views.add_edit_role,
        name='boards_add_role'),
    url(r'^edit_role/(?P<role_id>\d+)$',
        views.add_edit_role,
        name='boards_edit_role'),
    url(r'^delete_role/(?P<role_id>\d+)$',
        views.delete_role,
        name='boards_delete_role'),

    url(r'^board/(?P<board_id>\d+)$',
        views.view_board,
        name='boards_view_board'),
    url(r'^add_board/$',
        views.add_edit_board,
        name='boards_add_board'),
    url(r'^edit_board/(?P<board_id>\d+)$',
        views.add_edit_board,
        name='boards_edit_board'),
    url(r'^delete_board/(?P<board_id>\d+)$',
        views.delete_board,
        name='boards_delete_board'),

    url(r'^boardtype/(?P<boardtype_id>\d+)$',
        views.view_boardtype,
        name='boards_view_boardtype'),
    url(r'^add_boardtype/$',
        views.add_edit_boardtype,
        name='boards_add_boardtype'),
    url(r'^edit_boardtype/(?P<boardtype_id>\d+)$',
        views.add_edit_boardtype,
        name='boards_edit_boardtype'),
    url(r'^delete_boardtype/(?P<boardtype_id>\d+)$',
        views.delete_boardtype,
        name='boards_delete_boardtype'),

    url(r'^member/(?P<member_id>\d+)$',
        views.view_boardmember,
        name='boards_view_boardmember'),

    url(r'^board/(?P<board_id>\d+)/add_boardmember/$',
        views.add_edit_boardmember,
        name='boards_add_boardmember'),
    url(r'^add_boardmember/$',
        views.add_edit_boardmember,
        name='boards_add_boardmember'),
    url(r'^edit_boardmember/(?P<boardmember_id>\d+)$',
        views.add_edit_boardmember,
        name='boards_edit_boardmember'),
    url(r'^delete_boardmember/(?P<boardmember_id>\d+)$',
        views.delete_boardmember,
        name='boards_delete_boardmember'),
]