# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20150901_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSMap2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(default='', max_length=250)),
                ('default', models.CharField(default='', max_length=250)),
                ('default_has_changed', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
