# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cssmap2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSSMap',
        ),
    ]
