# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    css/themes was removed in favor of css/. If site is configured to use css/themes, change it.
    :param apps:
    :param schema_editor:
    :return:
    """
    SiteConfiguration = apps.get_model("base", "SiteConfiguration")
    db_alias = schema_editor.connection.alias
    config, created = SiteConfiguration.objects.using(db_alias).get_or_create()
    if config.bootstrap_theme_url == "css/themes/bootstrap.min.css":
        config.bootstrap_theme_url = "css/bootstrap.min.css"
    if config.bootstrap_theme_mod_url == "css/themes/bootstrap-theme.min.css":
        config.bootstrap_theme_mod_url = "css/bootstrap-theme.min.css"
    config.save()


def reverse_func(apps, schema_editor):
    """
    Reverts above migration
    :param apps:
    :param schema_editor:
    :return:
    """
    SiteConfiguration = apps.get_model("base", "SiteConfiguration")
    db_alias = schema_editor.connection.alias
    config, created = SiteConfiguration.objects.using(db_alias).get_or_create()
    if config.bootstrap_theme_url == "css/bootstrap.min.css":
        config.bootstrap_theme_url = "css/themes/bootstrap.min.css"
    if config.bootstrap_theme_mod_url == "css/bootstrap-theme.min.css":
        config.bootstrap_theme_mod_url = "css/themes/bootstrap-theme.min.css"
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_cssmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bootstrap_theme_mod_url',
            field=models.CharField(blank=True, default='css/bootstrap-theme.min.css', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bootstrap_theme_url',
            field=models.CharField(default='css/bootstrap.min.css', max_length=200),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
