# coding=utf-8
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from solo.models import SingletonModel
from django.dispatch import receiver
from django.db.models.signals import post_delete, pre_save, post_save
from .register import VIEW_MEMBER, VIEW_PUBLIC, VIEW_BOARD, EDIT
from users.permissions import has_user_perm

from base.models import Comment
from base.fields import ValidatedRichTextField
from base.html_stripper import strip_html

PERMISSION_CHOICES = (
    (VIEW_PUBLIC, "Visible for everyone"),
    (VIEW_MEMBER, "Visible for members"),
    (VIEW_BOARD, "Visible for board members"),
)


class Category(models.Model):
    """
    Model used to put pages in categories.
    A category can have many pages, but it's not nestable (category in category).
    """
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("news_home", kwargs={'category_name': self.name})

    def __str__(self):
        return self.name


class Article(models.Model):
    """
    News article.
    """
    title = models.CharField(max_length=100)
    summary = models.TextField(max_length=300, blank=True, null=True)
    slug = models.SlugField(editable=False)
    text = ValidatedRichTextField()
    search_text = models.TextField(editable=False, blank=True)
    # split the date and time in order to make fetching articles based on date easier
    created_date = models.DateField(auto_now_add=True)
    created_time = models.TimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # A small thumbnail used in the news feed
    picture = models.ImageField(upload_to="news/article_thumbnails", blank=True, null=True,
                                help_text="A small picture used in the news feed")
    author = models.ForeignKey(User)
    categories = models.ManyToManyField(Category, blank=True)
    permission = models.CharField(max_length=100, choices=PERMISSION_CHOICES, default="VIEW_PUBLIC")

    class Meta:
        ordering = ["-created_date", "-created_time"]
        unique_together = ("slug", "created_date")

    def get_summary(self):
        """
        Returns a short summary of the article.
        It can either be manually added or autogenerated from the content
        :return:
        """
        if self.summary:
            return self.summary
        else:
            if len(self.text) > 300:
                summary = ValidatedRichTextField.get_summary(self.text, 300)
                return "%s<p><strong>...</strong></p>" % summary
            else:
                return self.text

    def comments(self):
        """
        :return: A QuerySet of the comments for this object
        """
        return Comment.get_comments_for_object(self)

    def get_absolute_url(self):
        """

        :return: absolute url
        """
        return reverse("news_view_article", kwargs={'slug': self.slug,
                                                    'year': self.created_date.year,
                                                    'month': self.created_date.month,
                                                    'day': self.created_date.day})

    def __str__(self):
        return self.title

    def can_view(self, user):
        """
        :param self:
        :param user:
        :return: true if the user is allowed to view the article
        """
        return has_user_perm(user, self.permission)

    @staticmethod
    def can_edit(user):
        """
        :param user:
        :return: true if the user has the edit permission for news articles
        """
        return has_user_perm(user, EDIT)


@receiver(pre_save, sender=Article, dispatch_uid="article_pre_save")
def article_pre_save(**kwargs):
    """
    Creates a slug for the article.
    :param kwargs:
    :return:
    """
    instance = kwargs.pop("instance")
    # create slug at creation
    if not instance.pk:
        instance.slug = slugify(instance.title)
    # create search text
    instance.search_text = strip_html(instance.text).replace('\n', '').replace('\r', '')


class NewsSettings(SingletonModel):
    """
    Keeps track of settings for the news module
    """
    is_setup = models.BooleanField(default=False)
    number_of_articles_on_frontpage = models.IntegerField(default=5)

    @classmethod
    def instance(cls):
        """
        Returns the instance of news settings.
        :return:
        """
        self, created = cls.objects.get_or_create()
        return self
